version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
  exclusions:
    paths:
      - vendor/
      - docs/
    rules:
      - path: _test\.go
        linters:
          - errcheck
